package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// Config holds the conversion configuration
type Config struct {
	PackageName      string
	OutputStyle      string
	NamingConvention string
	IncludeTags      bool
	Tags             []string
	PointerTypes     bool
	CustomTypes      map[string]string
}

// Field represents a Go struct field
type Field struct {
	Name    string
	Type    string
	Tag     string
	Comment string
}

// StructDef represents a Go struct definition
type StructDef struct {
	Name    string
	Fields  []Field
	Comment string
}

func main() {
	cfg := Config{
		PackageName:      "models",
		OutputStyle:      "struct",
		NamingConvention: "pascal",
		IncludeTags:      true,
		Tags:             []string{"json", "yaml"},
		PointerTypes:     false,
	}

	args := os.Args[1:]
	files := []string{}

	for i, arg := range args {
		switch arg {
		case "--package", "-p":
			if i+1 < len(args) {
				cfg.PackageName = args[i+1]
			}
		case "--style", "-s":
			if i+1 < len(args) {
				cfg.OutputStyle = args[i+1]
			}
		case "--naming", "-n":
			if i+1 < len(args) {
				cfg.NamingConvention = args[i+1]
			}
		case "--no-tags":
			cfg.IncludeTags = false
		case "--tags":
			if i+1 < len(args) {
				cfg.Tags = strings.Split(args[i+1], ",")
			}
		case "--pointers":
			cfg.PointerTypes = true
		case "--help", "-h":
			printUsage()
			return
		default:
			if !strings.HasPrefix(arg, "-") {
				files = append(files, arg)
			}
		}
	}

	if len(files) == 0 {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading stdin: %v\n", err)
			os.Exit(1)
		}
		if len(data) > 0 {
			err = convertYAML(data, cfg, os.Stdout)
		} else {
			fmt.Fprintln(os.Stderr, "Error: no input provided. Use file arguments or pipe YAML to stdin.")
			os.Exit(1)
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", file, err)
			os.Exit(1)
		}
		err = convertYAML(data, cfg, os.Stdout)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error processing %s: %v\n", file, err)
			os.Exit(1)
		}
	}
}

func printUsage() {
	fmt.Println("yaml2go - Convert YAML files to Go structs")
	fmt.Println()
	fmt.Println("Usage: yaml2go [options] [file.yaml ...]")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --package, -p string    Package name (default: models)")
	fmt.Println("  --style, -s string      Output style: struct or all (default: struct)")
	fmt.Println("  --naming, -n string     Naming convention: pascal, camel, snake (default: pascal)")
	fmt.Println("  --no-tags               Disable field tags")
	fmt.Println("  --tags string           Comma-separated tags to include (default: json,yaml)")
	fmt.Println("  --pointers              Use pointer types for optional fields")
	fmt.Println("  --help, -h              Show this help")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  yaml2go config.yaml")
	fmt.Println("  yaml2go -p api k8s.yaml")
	fmt.Println("  cat config.yaml | yaml2go")
	fmt.Println("  yaml2go --naming camel --no-tags spec.yaml")
}

func convertYAML(data []byte, cfg Config, w io.Writer) error {
	var nodes []*yaml.Node
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	for {
		var node yaml.Node
		err := decoder.Decode(&node)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("invalid YAML: %w", err)
		}
		if node.Kind == yaml.DocumentNode {
			nodes = append(nodes, node.Content[0])
		} else if node.Kind == yaml.MappingNode {
			nodes = append(nodes, &node)
		}
	}

	if len(nodes) == 0 {
		return nil
	}

	structs := make([]StructDef, 0, len(nodes))

	if len(nodes) == 1 {
		name := inferStructName(nodes[0], cfg.NamingConvention)
		s := StructDef{Name: name}
		s.Fields, s.Comment = processNode(nodes[0], 0, cfg)
		structs = append(structs, s)
	} else {
		for _, node := range nodes {
			name := inferStructName(node, cfg.NamingConvention)
			s := StructDef{Name: name}
			s.Fields, _ = processNode(node, 0, cfg)
			structs = append(structs, s)
		}
	}

	writeGoCode(w, cfg, structs)
	return nil
}

func writeGoCode(w io.Writer, cfg Config, structs []StructDef) {
	fmt.Fprintf(w, "// Code generated by yaml2go. DO NOT EDIT.\n")
	fmt.Fprintf(w, "// Generated from YAML.\n\n")
	fmt.Fprintf(w, "package %s\n\n", cfg.PackageName)

	for _, s := range structs {
		if s.Comment != "" {
			fmt.Fprintf(w, "// %s\n", s.Comment)
		}
		fmt.Fprintf(w, "type %s struct {\n", s.Name)
		for _, f := range s.Fields {
			if f.Comment != "" {
				fmt.Fprintf(w, "\t// %s\n", f.Comment)
			}
			fmt.Fprintf(w, "\t%s %s", f.Name, f.Type)
			if cfg.IncludeTags && len(f.Tag) > 0 {
				fmt.Fprintf(w, " `%s`", f.Tag)
			}
			fmt.Fprintf(w, "\n")
		}
		fmt.Fprintf(w, "}\n\n")
	}
}

func processNode(node *yaml.Node, depth int, cfg Config) ([]Field, string) {
	if node == nil {
		return nil, ""
	}

	fields := []Field{}

	if node.Kind == yaml.MappingNode {
		for i := 0; i < len(node.Content); i += 2 {
			keyNode := node.Content[i]
			valueNode := node.Content[i+1]

			fieldName := keyNode.Value
			if cfg.NamingConvention != "" {
				fieldName = toFieldName(fieldName, cfg.NamingConvention)
			}

			fieldType, tag, nestedComment := extractField(valueNode, cfg)

			if depth >= 0 && len(tag) == 0 && cfg.IncludeTags {
				tag = buildTag(fieldName, cfg.Tags)
			}

			fields = append(fields, Field{
				Name:    fieldName,
				Type:    fieldType,
				Tag:     tag,
				Comment: nestedComment,
			})
		}
	} else {
		fieldType, _, _ := extractField(node, cfg)
		fields = append(fields, Field{
			Name: "Data",
			Type: fieldType,
			Tag:  buildTag("data", cfg.Tags),
		})
	}

	return fields, ""
}

func extractField(node *yaml.Node, cfg Config) (string, string, string) {
	if node == nil {
		return "interface{}", "", ""
	}

	switch node.Kind {
	case yaml.MappingNode:
		nestedFields, nestedComment := processNode(node, -1, cfg)
		goCode := inlineStruct(nestedFields)
		return goCode, "", nestedComment

	case yaml.SequenceNode:
		if len(node.Content) == 0 {
			return "[]interface{}", "", ""
		}
		elemType, _, _ := extractField(node.Content[0], cfg)
		return fmt.Sprintf("[]%s", elemType), "", ""

	case yaml.ScalarNode:
		return inferScalarType(node, cfg.CustomTypes), "", ""

	case yaml.AliasNode:
		return extractField(node.Alias, cfg)

	default:
		return "interface{}", "", ""
	}
}

func inferScalarType(node *yaml.Node, customTypes map[string]string) string {
	if node.Kind != yaml.ScalarNode {
		return "interface{}"
	}

	switch node.Tag {
	case "!!bool":
		return "bool"
	case "!!int":
		return "int64"
	case "!!float":
		return "float64"
	case "!!str":
		val := node.Value
		if isBoolPattern(val) {
			return "bool"
		}
		if isIntPattern(val) {
			return "int64"
		}
		if isFloatPattern(val) {
			return "float64"
		}
		return "string"
	case "!!null":
		return "string"
	case "!!map":
		return "map[string]interface{}"
	case "!!seq":
		return "[]interface{}"
	default:
		if gt, ok := customTypes[node.Tag]; ok {
			return gt
		}
		return "string"
	}
}

func inlineStruct(fields []Field) string {
	if len(fields) == 0 {
		return "struct{}"
	}

	buf := &strings.Builder{}
	buf.WriteString("struct {")

	for _, f := range fields {
		buf.WriteString("\n\t")
		buf.WriteString(f.Name)
		buf.WriteString(" ")
		buf.WriteString(f.Type)
		if len(f.Tag) > 0 {
			buf.WriteString(" ")
			buf.WriteString(f.Tag)
		}
	}
	buf.WriteString("\n\t_ struct{} // ensures package reference\n")
	buf.WriteString("}")

	return buf.String()
}

func toFieldName(name, convention string) string {
	if convention == "snake" {
		return name // already snake_case
	}
	if convention == "camel" {
		return toCamelCase(name)
	}
	return toPascalCase(name)
}

func toPascalCase(s string) string {
	parts := splitIntoParts(s)
	result := ""
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result += strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return result
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return pascal
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

func splitIntoParts(s string) []string {
	if len(s) == 0 {
		return []string{s}
	}

	runes := []rune(s)
	parts := []string{}
	current := []rune{}

	for i := 0; i < len(runes); i++ {
		r := runes[i]

		// Handle camelCase boundaries
		if i > 0 && i < len(runes)-1 {
			if runes[i-1] >= 'a' && runes[i-1] <= 'z' && r >= 'A' && r <= 'Z' {
				if len(current) > 0 {
					parts = append(parts, string(current))
					current = nil
				}
			}
		}

		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			current = append(current, r)
		} else {
			if len(current) > 0 {
				parts = append(parts, string(current))
				current = nil
			}
		}
	}
	if len(current) > 0 {
		parts = append(parts, string(current))
	}
	if len(parts) == 0 {
		return []string{s}
	}
	return parts
}

func buildTag(fieldName string, tagNames []string) string {
	if len(tagNames) == 0 {
		return ""
	}
	parts := []string{}
	for _, tag := range tagNames {
		parts = append(parts, fmt.Sprintf(`%s:"%s"`, tag, strings.ToLower(fieldName)))
	}
	return strings.Join(parts, " ")
}

func inferStructName(node *yaml.Node, convention string) string {
	if node.Kind == yaml.MappingNode && len(node.Content) > 0 {
		firstKey := node.Content[0].Value
		if convention == "camel" {
			return toCamelCase(firstKey)
		}
		return toPascalCase(firstKey)
	}
	return "Config"
}

func isBoolPattern(val string) bool {
	lower := strings.ToLower(val)
	return lower == "true" || lower == "false" || lower == "yes" || lower == "no"
}

func isIntPattern(val string) bool {
	for i, r := range val {
		if i == 0 && (r == '-' || r == '+') {
			continue
		}
		if r < '0' || r > '9' {
			return false
		}
	}
	return len(val) > 0
}

func isFloatPattern(val string) bool {
	dot := false
	for i, r := range val {
		if i == 0 && (r == '-' || r == '+') {
			continue
		}
		if r == '.' {
			if dot {
				return false
			}
			dot = true
			continue
		}
		if r < '0' || r > '9' {
			return false
		}
	}
	return dot
}
